### ISSUE TITLE
My instance of bot is broken!

### ISSUE THREAD

**Issue by vdv73rus** [Andrew8xx8/kirpich#22]
Here is the log

```{"message":"Recived [чот не оч] From [U06EKRFAQ]","@timestamp":"2016-01-25T08:59:55.739+00:00","@version":"1","severity":"INFO","host":"ruby"}
{"message":"Recived [Паш, еще] From [U06EKPBG9]","@timestamp":"2016-01-25T09:00:01.239+00:00","@version":"1","severity":"INFO","host":"ruby"}
/home/admin/kirpich/lib/kirpich/bot.rb:41:in `eval_answer': wrong number of arguments (1 for 3) (ArgumentError)
	from /home/admin/kirpich/lib/kirpich/bot.rb:71:in `random_response'
	from /home/admin/kirpich/lib/kirpich/bot.rb:79:in `block in random_post_timer'
	from /home/admin/kirpich/lib/kirpich/client.rb:13:in `block in post_after'
	from /home/admin/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `call'
	from /home/admin/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
	from /home/admin/.rvm/gems/ruby-2.2.3/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
	from /home/admin/.rvm/gems/ruby-2.2.3/gems/slack-api-1.1.6/lib/slack/realtime/client.rb:18:in `start'
	from /home/admin/kirpich/lib/kirpich.rb:58:in `run'
	from bin/run:8:in `block in <main>'
	from /home/admin/.rvm/gems/ruby-2.2.3/gems/dante-0.2.0/lib/dante/runner.rb:123:in `call'
	from /home/admin/.rvm/gems/ruby-2.2.3/gems/dante-0.2.0/lib/dante/runner.rb:123:in `start'
	from /home/admin/.rvm/gems/ruby-2.2.3/gems/dante-0.2.0/lib/dante/runner.rb:74:in `execute'
	from /home/admin/.rvm/gems/ruby-2.2.3/gems/dante-0.2.0/lib/dante.rb:24:in `run'
	from bin/run:7:in `<main>'
```

**Comment by Andrew8xx8** [comment]
хоккей с мячем

**Comment by Andrew8xx8** [comment]
Исправлено тут https://github.com/Andrew8xx8/kirpich/commit/5af492b0d2f58eb4370a098dfa3af4c69a0355c4
