### ISSUE TITLE
Паша падает иногда

### ISSUE THREAD

**Issue by IvanUshakov** [Andrew8xx8/kirpich#23]
Сейчас постоянно ловим такую фигню:
```
2016-03-09T09:31:51.618698+00:00 app[worker.1]: Starting kirpich service...
2016-03-09T09:31:51.618730+00:00 app[worker.1]: {"message":"I am touch!","@timestamp":"2016-03-09T09:31:36.729+00:00","@version":"1","severity":"INFO","host":"09ad4593-38e5-49d4-8a4d-7d84778dc6be"}
2016-03-09T09:31:51.618733+00:00 app[worker.1]: {"message":"Recived [Паш, ты тут?] From [U0BFT13D1]","@timestamp":"2016-03-09T09:31:42.265+00:00","@version":"1","severity":"INFO","host":"09ad4593-38e5-49d4-8a4d-7d84778dc6be"}
2016-03-09T09:31:51.618735+00:00 app[worker.1]: {"message":"Respond with choose_text","@timestamp":"2016-03-09T09:31:42.267+00:00","@version":"1","severity":"INFO","host":"09ad4593-38e5-49d4-8a4d-7d84778dc6be"}
2016-03-09T09:31:51.618736+00:00 app[worker.1]: {"message":"Recived [Паш, постни котиков] From [U0BFT13D1]","@timestamp":"2016-03-09T09:31:51.605+00:00","@version":"1","severity":"INFO","host":"09ad4593-38e5-49d4-8a4d-7d84778dc6be"}
2016-03-09T09:31:52.415347+00:00 heroku[worker.1]: Process exited with status 1
2016-03-09T09:31:52.417667+00:00 heroku[worker.1]: State changed from up to crashed
2016-03-09T09:32:05.390856+00:00 heroku[worker.1]: State changed from crashed to starting
2016-03-09T09:32:11.912251+00:00 heroku[worker.1]: Starting process with command `bundle exec bin/run`
2016-03-09T09:32:12.500515+00:00 heroku[worker.1]: State changed from starting to up
2016-03-09T09:32:13.383420+00:00 app[worker.1]: Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
2016-03-09T09:32:13.383406+00:00 app[worker.1]: fatal: Not a git repository (or any parent up to mount point /app)
2016-03-09T09:33:02.790413+00:00 app[worker.1]: /app/lib/kirpich/brain.rb:70:in `on_call': undefined local variable or method `random_post' for Kirpich::Brain:Class (NameError)
2016-03-09T09:33:02.790443+00:00 app[worker.1]:     from /app/lib/kirpich/brain.rb:22:in `respond_on'
2016-03-09T09:33:02.790445+00:00 app[worker.1]:     from /app/lib/kirpich/bot.rb:15:in `on_message'
2016-03-09T09:33:02.790450+00:00 app[worker.1]:     from /app/lib/kirpich.rb:38:in `block in run'
2016-03-09T09:33:02.790451+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/slack-api-1.1.6/lib/slack/realtime/client.rb:28:in `call'
2016-03-09T09:33:02.790474+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/slack-api-1.1.6/lib/slack/realtime/client.rb:28:in `block (3 levels) in start'
2016-03-09T09:33:02.790476+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/slack-api-1.1.6/lib/slack/realtime/client.rb:27:in `each'
2016-03-09T09:33:02.790476+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/slack-api-1.1.6/lib/slack/realtime/client.rb:27:in `block (2 levels) in start'
2016-03-09T09:33:02.790477+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/event_emitter.rb:39:in `call'
2016-03-09T09:33:02.790477+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
2016-03-09T09:33:02.790478+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/event_emitter.rb:38:in `each'
2016-03-09T09:33:02.790478+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/event_emitter.rb:38:in `emit'
2016-03-09T09:33:02.790479+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api/event_target.rb:44:in `dispatch_event'
2016-03-09T09:33:02.790479+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api.rb:95:in `receive_message'
2016-03-09T09:33:02.790480+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api.rb:38:in `block in initialize'
2016-03-09T09:33:02.790480+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/event_emitter.rb:39:in `call'
2016-03-09T09:33:02.790481+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
2016-03-09T09:33:02.790482+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/event_emitter.rb:38:in `each'
2016-03-09T09:33:02.790482+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/event_emitter.rb:38:in `emit'
2016-03-09T09:33:02.790483+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/hybi.rb:400:in `emit_message'
2016-03-09T09:33:02.790483+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/hybi.rb:383:in `emit_frame'
2016-03-09T09:33:02.790484+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/hybi.rb:121:in `parse'
2016-03-09T09:33:02.790484+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/websocket-driver-0.6.2/lib/websocket/driver/client.rb:57:in `parse'
2016-03-09T09:33:02.790485+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/faye-websocket-0.9.2/lib/faye/websocket/api.rb:134:in `parse'
2016-03-09T09:33:02.790486+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/faye-websocket-0.9.2/lib/faye/websocket/client.rb:77:in `receive_data'
2016-03-09T09:33:02.790486+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
2016-03-09T09:33:02.790487+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
2016-03-09T09:33:02.790488+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/slack-api-1.1.6/lib/slack/realtime/client.rb:18:in `start'
2016-03-09T09:33:02.790488+00:00 app[worker.1]:     from /app/lib/kirpich.rb:58:in `run'
2016-03-09T09:33:02.790489+00:00 app[worker.1]:     from bin/run:8:in `block in <main>'
2016-03-09T09:33:02.790489+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/dante-0.2.0/lib/dante/runner.rb:123:in `call'
2016-03-09T09:33:02.790490+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/dante-0.2.0/lib/dante/runner.rb:123:in `start'
2016-03-09T09:33:02.790491+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/dante-0.2.0/lib/dante/runner.rb:74:in `execute'
2016-03-09T09:33:02.790492+00:00 app[worker.1]:     from /app/vendor/bundle/ruby/2.2.0/gems/dante-0.2.0/lib/dante.rb:24:in `run'
2016-03-09T09:33:02.790495+00:00 app[worker.1]:     from bin/run:7:in `<main>'
2016-03-09T09:33:02.797822+00:00 app[worker.1]: Starting kirpich service...
2016-03-09T09:33:02.797835+00:00 app[worker.1]: {"message":"I am touch!","@timestamp":"2016-03-09T09:32:14.970+00:00","@version":"1","severity":"INFO","host":"c9a6006f-4888-4e48-ab2c-6a1ac148401b"}
2016-03-09T09:33:02.797836+00:00 app[worker.1]: {"message":"Recived [Паш, постни котиков] From [U0BFT13D1]","@timestamp":"2016-03-09T09:33:02.789+00:00","@version":"1","severity":"INFO","host":"c9a6006f-4888-4e48-ab2c-6a1ac148401b"}
2016-03-09T09:33:03.336910+00:00 heroku[worker.1]: Process exited with status 1
2016-03-09T09:33:03.332439+00:00 heroku[worker.1]: State changed from up to crashed
```

Метода random_post нигде не нашё

**Comment by IvanUshakov** [comment]
👏
